{"message":"Error thrown while running command \"list --format=xml\". Message: \"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found\"","context":{"exception":{"class":"Error","message":"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35"},"command":"list --format=xml","message":"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found"},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2025-02-26T18:59:37.480185+00:00","extra":{}}
{"message":"Uncaught Error: Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found","context":{"exception":{"class":"Error","message":"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35"}},"level":500,"level_name":"CRITICAL","channel":"php","datetime":"2025-02-26T18:59:37.486487+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T19:06:41.720524+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"Cannot assign string to property App\\Entity\\Task::$assignedUser of type ?App\\Entity\\User\" at Task.php line 48","context":{"exception":{"class":"TypeError","message":"Cannot assign string to property App\\Entity\\Task::$assignedUser of type ?App\\Entity\\User","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Entity\\Task.php:48"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T19:08:01.593154+00:00","extra":{}}
{"message":"Uncaught PHP Exception Symfony\\Component\\ErrorHandler\\Error\\FatalError: \"Error: Maximum execution time of 30 seconds exceeded\" at Driver.php line 40","context":{"exception":{"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","message":"Error: Maximum execution time of 30 seconds exceeded","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\PgSQL\\Driver.php:40"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T22:57:59.236151+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T22:58:27.349257+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T22:58:31.102236+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T22:58:32.923384+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T22:58:34.571848+00:00","extra":{}}
{"message":"Uncaught PHP Exception TypeError: \"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50\" at UserAuthenticator.php line 93","context":{"exception":{"class":"TypeError","message":"App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T23:00:55.112843+00:00","extra":{}}
{"message":"Uncaught PHP Exception RedisException: \"No connection could be made because the target machine actively refused it\" at PhpredisClientFactory.php line 247","context":{"exception":{"class":"RedisException","message":"No connection could be made because the target machine actively refused it","code":0,"file":"E:\\Export\\Task Management system Symfony\\task_management\\vendor\\snc\\redis-bundle\\src\\Factory\\PhpredisClientFactory.php:247"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2025-02-26T23:48:38.569164+00:00","extra":{}}
